require: rubocop-rspec

AllCops:
  Exclude:
    - 'Gemfile'
    - 'Rakefile'
    - 'bin/console'
    - 'expire.gemspec'
    - 'spec/spec_helper.rb'
  NewCops: enable

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Layout/HashAlignment:
  EnforcedColonStyle: table

Naming/VariableNumber:
  EnforcedStyle: snake_case

RSpec/DescribeClass:
  Enabled: true
  Exclude:
    - 'spec/integration/*'

RSpec/FilePath:
  Enabled: true
  Exclude:
    - 'spec/unit/*'

RSpec/ImplicitExpect:
  Enabled: false

Lint/MissingSuper:
  Enabled: true
  Exclude:
    - lib/expire/commands/*

Lint/UnusedMethodArgument:
  Enabled: true
  Exclude:
    - lib/expire/commands/*
